import "./globals.css";
import { ReduxProvider } from "@/redux/provider";

export const metadata = {
  title: "Url Shortner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>{children}</body>
      </ReduxProvider>
    </html>
  );
}
